### ISSUE TITLE
training with default hyper parameters didn't get the similar results as provided pretrained model

### ISSUE THREAD

**Issue by niujinshuchong** [fuy34/planerecover#1] opened 2018-09-18 15:18 UTC
Thank you for sharing the work. 
I train the network with default hyper parameters and didn't get the similar results as the provided pretrained model. Mainly, predicted plane using my trained model  contains different plane. The left building wall and the right building wall were predicted as same plane and the predicted parameter is pointed to camera. However, there is in fact two plane and one is pointed to left and the other right.
I wonder if there are some training details not contained in the release code, such as initialization or training policy?

**Comment by fuy34** [comment] 2018-09-18 18:01
Thanks for your interest in our work. 
We did realize different system environment (e.g. different Tensorflow versions, Cuda versions, etc) may lead to a different result (such as the situation you mentioned).  We doubt it may be caused by the optimization or random initialization process. We are working on a more stable version.

Based on our experience, currently, tuning the plane_weight a little bit usually can solve this problem. Some effective plane_weight we have tried in different devices include (0.08, 0.092, 0.11, 0.13). In general, do a grid search in the range [0.08, 0.13] should work.

**Comment by niujinshuchong** [comment] 2018-09-19 02:10
Thank you for nice reply.
I will train with different plane_weight. I will let you know once the experiments is done.

**Comment by fuy34** [comment] 2018-09-19 23:53
Thanks, I will close this issues, but feel free to contact us if there is any other issues, and please let us know if you find any method or new weight could make the code more robust.

**Closed as completed by fuy34** 2018-09-19 23:53 UTC

**Comment by Huangying-Zhan** [comment] 2018-10-28 04:30
Hi @niujinshuchong,  Did you solve the problem? I got a similar issue in my experiment. 
I got something like this. Please let me know if you found a good way in solving it.
![image](https://user-images.githubusercontent.com/13748721/47612040-1b388680-dac2-11e8-8d0d-98605210846f.png)
